# Dockerfile do frontend
FROM nginx:latest

COPY index.html /usr/share/nginx/html
COPY style /usr/share/nginx/html/style
COPY scripts /usr/share/nginx/html/scripts

EXPOSE 80

# Adiciona o comando para iniciar o servidor nginx
CMD ["nginx", "-g", "daemon off;"]